// Generated by the Supabase MCP / CLI from the live schema (ARCHITECTURE.md §7).
// Do NOT edit by hand. Regenerate after any migration:
//   supabase gen types typescript --project-id vrcnbvijanpxrqwndnyl > src/lib/database.types.ts
// The hand-written domain types in ./types.ts remain the canonical contract the
// UI codes against; this file is the raw row/insert/update shapes for the client.
//
// HAND-EXTENDED (2026-07-03, v2): the `profiles`, `subscriptions`,
// `stripe_events` and `fixture_insights` tables below are added by hand,
// matching the migration 0004 contract the backend-jobs lane is landing
// concurrently (ARCHITECTURE.md §7 v2 amendment). The main session regenerates
// this whole file from the live DB once that migration is applied — at that
// point this hand-written block should be replaced by the generator's output,
// not merged with it.
//
// HAND-EXTENDED (2026-07-03, v3): `top_scorers` (Golden Boot standings) is
// likewise added by hand, matching the migration the backend-jobs lane is
// landing concurrently this round — league_id FK, api_player_id, player_name,
// team_name, nationality, goals, assists, penalties, rank, updated_at; PK
// (league_id, api_player_id); anon-readable like fixtures. The FK constraint
// name below (`top_scorers_league_id_fkey`) follows this schema's existing
// `<table>_<column>_fkey` convention but is NOT verified against the live
// migration — the web queries deliberately avoid depending on this exact
// constraint name (see lib/queries/goldenBoot.ts), so a mismatch degrades to
// an honest empty state rather than a broken build.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      fixtures: {
        Row: {
          api_fixture_id: number
          away_team_id: number
          created_at: string
          final_away_goals: number | null
          final_home_goals: number | null
          home_team_id: number
          id: number
          kickoff_utc: string
          league_id: number
          status: string
          updated_at: string
        }
        Insert: {
          api_fixture_id: number
          away_team_id: number
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          home_team_id: number
          id?: never
          kickoff_utc: string
          league_id: number
          status?: string
          updated_at?: string
        }
        Update: {
          api_fixture_id?: number
          away_team_id?: number
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          home_team_id?: number
          id?: never
          kickoff_utc?: string
          league_id?: number
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fixtures_away_team_id_fkey"
            columns: ["away_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fixtures_home_team_id_fkey"
            columns: ["home_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fixtures_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
        ]
      }
      leagues: {
        Row: {
          api_league_id: number
          country: string
          id: number
          name: string
          season: number
          slug: string
        }
        Insert: {
          api_league_id: number
          country: string
          id?: never
          name: string
          season: number
          slug: string
        }
        Update: {
          api_league_id?: number
          country?: string
          id?: never
          name?: string
          season?: number
          slug?: string
        }
        Relationships: []
      }
      predictions: {
        Row: {
          brier_score: number | null
          created_at: string
          final_away_goals: number | null
          final_home_goals: number | null
          fixture_id: number
          id: string
          locked_at: string
          log_loss: number | null
          model_version: string
          predicted_away_goals: number
          predicted_home_goals: number
          prob_away: number
          prob_draw: number
          prob_home: number
          published_at: string
          result: string | null
          scored_at: string | null
          source: string
          status: string
          tier: string
        }
        Insert: {
          brier_score?: number | null
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          fixture_id: number
          id?: string
          locked_at: string
          log_loss?: number | null
          model_version: string
          predicted_away_goals: number
          predicted_home_goals: number
          prob_away: number
          prob_draw: number
          prob_home: number
          published_at?: string
          result?: string | null
          scored_at?: string | null
          source: string
          status?: string
          tier?: string
        }
        Update: {
          brier_score?: number | null
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          fixture_id?: number
          id?: string
          locked_at?: string
          log_loss?: number | null
          model_version?: string
          predicted_away_goals?: number
          predicted_home_goals?: number
          prob_away?: number
          prob_draw?: number
          prob_home?: number
          published_at?: string
          result?: string | null
          scored_at?: string | null
          source?: string
          status?: string
          tier?: string
        }
        Relationships: [
          {
            foreignKeyName: "predictions_fixture_id_fkey"
            columns: ["fixture_id"]
            isOneToOne: false
            referencedRelation: "fixtures"
            referencedColumns: ["id"]
          },
        ]
      }
      teams: {
        Row: {
          api_team_id: number
          id: number
          league_id: number
          name: string
          slug: string
        }
        Insert: {
          api_team_id: number
          id?: never
          league_id: number
          name: string
          slug: string
        }
        Update: {
          api_team_id?: number
          id?: never
          league_id?: number
          name?: string
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "teams_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
        ]
      }
      // ── v2 premium tables (hand-extended — see file header note) ──────
      profiles: {
        Row: {
          id: string
          created_at: string
          is_18_plus: boolean
          marketing_opt_in: boolean
        }
        Insert: {
          id: string
          created_at?: string
          is_18_plus?: boolean
          marketing_opt_in?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          is_18_plus?: boolean
          marketing_opt_in?: boolean
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          id: string
          user_id: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          status: string
          price_id: string | null
          current_period_end: string | null
          cancel_at_period_end: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          status?: string
          price_id?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          status?: string
          price_id?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      stripe_events: {
        Row: {
          id: string
          type: string
          received_at: string
          payload: Json
        }
        Insert: {
          id: string
          type: string
          received_at?: string
          payload: Json
        }
        Update: {
          id?: string
          type?: string
          received_at?: string
          payload?: Json
        }
        Relationships: []
      }
      fixture_insights: {
        Row: {
          fixture_id: number
          kind: string
          payload: Json
          source: string
          fetched_at: string
        }
        Insert: {
          fixture_id: number
          kind: string
          payload: Json
          source: string
          fetched_at?: string
        }
        Update: {
          fixture_id?: number
          kind?: string
          payload?: Json
          source?: string
          fetched_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fixture_insights_fixture_id_fkey"
            columns: ["fixture_id"]
            isOneToOne: false
            referencedRelation: "fixtures"
            referencedColumns: ["id"]
          },
        ]
      }
      // ── v3 stats table (hand-extended — see file header note) ──────────
      top_scorers: {
        Row: {
          league_id: number
          api_player_id: number
          player_name: string
          team_name: string
          nationality: string
          goals: number
          assists: number
          penalties: number
          rank: number
          updated_at: string
        }
        Insert: {
          league_id: number
          api_player_id: number
          player_name: string
          team_name: string
          nationality: string
          goals?: number
          assists?: number
          penalties?: number
          rank: number
          updated_at?: string
        }
        Update: {
          league_id?: number
          api_player_id?: number
          player_name?: string
          team_name?: string
          nationality?: string
          goals?: number
          assists?: number
          penalties?: number
          rank?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "top_scorers_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
