// Generated by the Supabase MCP / CLI from the live schema (ARCHITECTURE.md §7).
// Do NOT edit by hand. Regenerate after any migration:
//   supabase gen types typescript --project-id vrcnbvijanpxrqwndnyl > src/lib/database.types.ts
// The hand-written domain types in ./types.ts remain the canonical contract the
// UI codes against; this file is the raw row/insert/update shapes for the client.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      email_send_log: {
        Row: {
          email: string
          id: number
          ip_hash: string
          sent_at: string
        }
        Insert: {
          email: string
          id?: never
          ip_hash: string
          sent_at?: string
        }
        Update: {
          email?: string
          id?: never
          ip_hash?: string
          sent_at?: string
        }
        Relationships: []
      }
      email_subscribers: {
        Row: {
          confirm_token: string
          confirmed_at: string | null
          consented_at: string
          created_at: string
          email: string
          id: string
          unsubscribe_token: string
        }
        Insert: {
          confirm_token?: string
          confirmed_at?: string | null
          consented_at?: string
          created_at?: string
          email: string
          id?: string
          unsubscribe_token?: string
        }
        Update: {
          confirm_token?: string
          confirmed_at?: string | null
          consented_at?: string
          created_at?: string
          email?: string
          id?: string
          unsubscribe_token?: string
        }
        Relationships: []
      }
      fixture_insights: {
        Row: {
          fetched_at: string
          fixture_id: number
          kind: string
          payload: Json
          source: string
        }
        Insert: {
          fetched_at?: string
          fixture_id: number
          kind: string
          payload: Json
          source?: string
        }
        Update: {
          fetched_at?: string
          fixture_id?: number
          kind?: string
          payload?: Json
          source?: string
        }
        Relationships: [
          {
            foreignKeyName: "fixture_insights_fixture_id_fkey"
            columns: ["fixture_id"]
            isOneToOne: false
            referencedRelation: "fixtures"
            referencedColumns: ["id"]
          },
        ]
      }
      fixture_pick_aggregates: {
        Row: {
          avg_prob_away: number | null
          avg_prob_draw: number | null
          avg_prob_home: number | null
          fixture_id: number
          n_picks: number
          updated_at: string
        }
        Insert: {
          avg_prob_away?: number | null
          avg_prob_draw?: number | null
          avg_prob_home?: number | null
          fixture_id: number
          n_picks?: number
          updated_at?: string
        }
        Update: {
          avg_prob_away?: number | null
          avg_prob_draw?: number | null
          avg_prob_home?: number | null
          fixture_id?: number
          n_picks?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fixture_pick_aggregates_fixture_id_fkey"
            columns: ["fixture_id"]
            isOneToOne: true
            referencedRelation: "fixtures"
            referencedColumns: ["id"]
          },
        ]
      }
      fixtures: {
        Row: {
          api_fixture_id: number
          api_round: string | null
          away_team_id: number
          created_at: string
          final_away_goals: number | null
          final_home_goals: number | null
          home_team_id: number
          id: number
          kickoff_utc: string
          league_id: number
          round: string | null
          status: string
          updated_at: string
          winner_team_id: number | null
        }
        Insert: {
          api_fixture_id: number
          api_round?: string | null
          away_team_id: number
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          home_team_id: number
          id?: never
          kickoff_utc: string
          league_id: number
          round?: string | null
          status?: string
          updated_at?: string
          winner_team_id?: number | null
        }
        Update: {
          api_fixture_id?: number
          api_round?: string | null
          away_team_id?: number
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          home_team_id?: number
          id?: never
          kickoff_utc?: string
          league_id?: number
          round?: string | null
          status?: string
          updated_at?: string
          winner_team_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "fixtures_away_team_id_fkey"
            columns: ["away_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fixtures_home_team_id_fkey"
            columns: ["home_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fixtures_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fixtures_winner_team_id_fkey"
            columns: ["winner_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      job_runs: {
        Row: {
          counts: Json | null
          created_at: string
          error: string | null
          finished_at: string | null
          id: number
          job: string
          ok: boolean | null
          started_at: string
        }
        Insert: {
          counts?: Json | null
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: never
          job: string
          ok?: boolean | null
          started_at: string
        }
        Update: {
          counts?: Json | null
          created_at?: string
          error?: string | null
          finished_at?: string | null
          id?: never
          job?: string
          ok?: boolean | null
          started_at?: string
        }
        Relationships: []
      }
      leaderboard_standings: {
        Row: {
          beat_margin: number
          display_name: string
          model_mean_brier: number
          picks_scored: number
          rank: number
          updated_at: string
          user_id: string
          user_mean_brier: number
        }
        Insert: {
          beat_margin: number
          display_name: string
          model_mean_brier: number
          picks_scored: number
          rank: number
          updated_at?: string
          user_id: string
          user_mean_brier: number
        }
        Update: {
          beat_margin?: number
          display_name?: string
          model_mean_brier?: number
          picks_scored?: number
          rank?: number
          updated_at?: string
          user_id?: string
          user_mean_brier?: number
        }
        Relationships: [
          {
            foreignKeyName: "leaderboard_standings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      leagues: {
        Row: {
          api_league_id: number
          country: string
          id: number
          name: string
          season: number
          slug: string
        }
        Insert: {
          api_league_id: number
          country: string
          id?: never
          name: string
          season: number
          slug: string
        }
        Update: {
          api_league_id?: number
          country?: string
          id?: never
          name?: string
          season?: number
          slug?: string
        }
        Relationships: []
      }
      ledger_checkpoints: {
        Row: {
          chain_hash: string
          created_at: string
          day: string
          id: number
          prev_hash: string | null
          scored_rows: number
        }
        Insert: {
          chain_hash: string
          created_at?: string
          day: string
          id?: never
          prev_hash?: string | null
          scored_rows: number
        }
        Update: {
          chain_hash?: string
          created_at?: string
          day?: string
          id?: never
          prev_hash?: string | null
          scored_rows?: number
        }
        Relationships: []
      }
      pool_members: {
        Row: {
          display_name: string
          joined_at: string
          pool_id: string
          user_id: string
        }
        Insert: {
          display_name: string
          joined_at?: string
          pool_id: string
          user_id: string
        }
        Update: {
          display_name?: string
          joined_at?: string
          pool_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pool_members_pool_id_fkey"
            columns: ["pool_id"]
            isOneToOne: false
            referencedRelation: "pools"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pool_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pools: {
        Row: {
          created_at: string
          id: string
          invite_code: string
          name: string
          owner_user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          invite_code?: string
          name: string
          owner_user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          invite_code?: string
          name?: string
          owner_user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "pools_owner_user_id_fkey"
            columns: ["owner_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      predictions: {
        Row: {
          brier_score: number | null
          created_at: string
          final_away_goals: number | null
          final_home_goals: number | null
          fixture_id: number
          id: string
          locked_at: string
          log_loss: number | null
          model_version: string
          narrative: string | null
          predicted_away_goals: number
          predicted_home_goals: number
          prob_away: number
          prob_draw: number
          prob_home: number
          published_at: string
          result: string | null
          scored_at: string | null
          source: string
          status: string
          tier: string
        }
        Insert: {
          brier_score?: number | null
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          fixture_id: number
          id?: string
          locked_at: string
          log_loss?: number | null
          model_version: string
          narrative?: string | null
          predicted_away_goals: number
          predicted_home_goals: number
          prob_away: number
          prob_draw: number
          prob_home: number
          published_at?: string
          result?: string | null
          scored_at?: string | null
          source: string
          status?: string
          tier?: string
        }
        Update: {
          brier_score?: number | null
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          fixture_id?: number
          id?: string
          locked_at?: string
          log_loss?: number | null
          model_version?: string
          narrative?: string | null
          predicted_away_goals?: number
          predicted_home_goals?: number
          prob_away?: number
          prob_draw?: number
          prob_home?: number
          published_at?: string
          result?: string | null
          scored_at?: string | null
          source?: string
          status?: string
          tier?: string
        }
        Relationships: [
          {
            foreignKeyName: "predictions_fixture_id_fkey"
            columns: ["fixture_id"]
            isOneToOne: false
            referencedRelation: "fixtures"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          id: string
          is_18_plus: boolean
          leaderboard_display_name: string | null
          leaderboard_opt_in: boolean
          marketing_opt_in: boolean
        }
        Insert: {
          created_at?: string
          id: string
          is_18_plus?: boolean
          leaderboard_display_name?: string | null
          leaderboard_opt_in?: boolean
          marketing_opt_in?: boolean
        }
        Update: {
          created_at?: string
          id?: string
          is_18_plus?: boolean
          leaderboard_display_name?: string | null
          leaderboard_opt_in?: boolean
          marketing_opt_in?: boolean
        }
        Relationships: []
      }
      stripe_events: {
        Row: {
          id: string
          payload: Json | null
          received_at: string
          type: string
        }
        Insert: {
          id: string
          payload?: Json | null
          received_at?: string
          type: string
        }
        Update: {
          id?: string
          payload?: Json | null
          received_at?: string
          type?: string
        }
        Relationships: []
      }
      subscriptions: {
        Row: {
          cancel_at_period_end: boolean
          created_at: string
          current_period_end: string | null
          id: string
          price_id: string | null
          status: string
          stripe_customer_id: string
          stripe_subscription_id: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          id?: string
          price_id?: string | null
          status: string
          stripe_customer_id: string
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          cancel_at_period_end?: boolean
          created_at?: string
          current_period_end?: string | null
          id?: string
          price_id?: string | null
          status?: string
          stripe_customer_id?: string
          stripe_subscription_id?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      team_probability_snapshots: {
        Row: {
          created_at: string
          delta_elo_rating: number | null
          delta_prob_win: number | null
          elo_rating: number
          expected_goals_against: number
          expected_goals_for: number
          fixture_id: number
          is_home: boolean
          opponent_team_id: number
          prob_clean_sheet: number
          prob_draw: number
          prob_loss: number
          prob_win: number
          snapshot_date: string
          team_id: number
        }
        Insert: {
          created_at?: string
          delta_elo_rating?: number | null
          delta_prob_win?: number | null
          elo_rating: number
          expected_goals_against: number
          expected_goals_for: number
          fixture_id: number
          is_home: boolean
          opponent_team_id: number
          prob_clean_sheet: number
          prob_draw: number
          prob_loss: number
          prob_win: number
          snapshot_date: string
          team_id: number
        }
        Update: {
          created_at?: string
          delta_elo_rating?: number | null
          delta_prob_win?: number | null
          elo_rating?: number
          expected_goals_against?: number
          expected_goals_for?: number
          fixture_id?: number
          is_home?: boolean
          opponent_team_id?: number
          prob_clean_sheet?: number
          prob_draw?: number
          prob_loss?: number
          prob_win?: number
          snapshot_date?: string
          team_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "team_probability_snapshots_fixture_id_fkey"
            columns: ["fixture_id"]
            isOneToOne: false
            referencedRelation: "fixtures"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_probability_snapshots_opponent_team_id_fkey"
            columns: ["opponent_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "team_probability_snapshots_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      teams: {
        Row: {
          api_team_id: number
          id: number
          league_id: number
          name: string
          slug: string
        }
        Insert: {
          api_team_id: number
          id?: never
          league_id: number
          name: string
          slug: string
        }
        Update: {
          api_team_id?: number
          id?: never
          league_id?: number
          name?: string
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "teams_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
        ]
      }
      top_scorers: {
        Row: {
          api_player_id: number
          assists: number | null
          goals: number
          league_id: number
          nationality: string | null
          penalties: number | null
          player_name: string
          rank: number
          team_name: string
          updated_at: string
        }
        Insert: {
          api_player_id: number
          assists?: number | null
          goals: number
          league_id: number
          nationality?: string | null
          penalties?: number | null
          player_name: string
          rank: number
          team_name: string
          updated_at?: string
        }
        Update: {
          api_player_id?: number
          assists?: number | null
          goals?: number
          league_id?: number
          nationality?: string | null
          penalties?: number | null
          player_name?: string
          rank?: number
          team_name?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "top_scorers_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
        ]
      }
      tournament_chances: {
        Row: {
          computed_at: string
          p_reach_final: number | null
          p_reach_semi: number | null
          p_win_tournament: number
          sims: number
          snapshot_date: string
          team_id: number
        }
        Insert: {
          computed_at?: string
          p_reach_final?: number | null
          p_reach_semi?: number | null
          p_win_tournament: number
          sims: number
          snapshot_date: string
          team_id: number
        }
        Update: {
          computed_at?: string
          p_reach_final?: number | null
          p_reach_semi?: number | null
          p_win_tournament?: number
          sims?: number
          snapshot_date?: string
          team_id?: number
        }
        Relationships: [
          {
            foreignKeyName: "tournament_chances_team_id_fkey"
            columns: ["team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
        ]
      }
      user_predictions: {
        Row: {
          brier_score: number | null
          created_at: string
          fixture_id: number
          id: string
          prob_away: number
          prob_draw: number
          prob_home: number
          result: string | null
          scored_at: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          brier_score?: number | null
          created_at?: string
          fixture_id: number
          id?: string
          prob_away: number
          prob_draw: number
          prob_home: number
          result?: string | null
          scored_at?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          brier_score?: number | null
          created_at?: string
          fixture_id?: number
          id?: string
          prob_away?: number
          prob_draw?: number
          prob_home?: number
          result?: string | null
          scored_at?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_predictions_fixture_id_fkey"
            columns: ["fixture_id"]
            isOneToOne: false
            referencedRelation: "fixtures"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "user_predictions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_pool_member: {
        Args: { p_pool_id: string; p_user_id: string }
        Returns: boolean
      }
      is_premium: { Args: { uid: string }; Returns: boolean }
      join_pool: {
        Args: { p_display_name: string; p_invite_code: string }
        Returns: Json
      }
      request_email_send: {
        Args: { p_email: string; p_ip_hash: string }
        Returns: boolean
      }
      teardown_season: { Args: { p_season: number }; Returns: Json }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never
