// Generated by the Supabase MCP / CLI from the live schema (ARCHITECTURE.md §7).
// Do NOT edit by hand. Regenerate after any migration:
//   supabase gen types typescript --project-id vrcnbvijanpxrqwndnyl > src/lib/database.types.ts
// The hand-written domain types in ./types.ts remain the canonical contract the
// UI codes against; this file is the raw row/insert/update shapes for the client.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      fixtures: {
        Row: {
          api_fixture_id: number
          away_team_id: number
          created_at: string
          final_away_goals: number | null
          final_home_goals: number | null
          home_team_id: number
          id: number
          kickoff_utc: string
          league_id: number
          status: string
          updated_at: string
        }
        Insert: {
          api_fixture_id: number
          away_team_id: number
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          home_team_id: number
          id?: never
          kickoff_utc: string
          league_id: number
          status?: string
          updated_at?: string
        }
        Update: {
          api_fixture_id?: number
          away_team_id?: number
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          home_team_id?: number
          id?: never
          kickoff_utc?: string
          league_id?: number
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fixtures_away_team_id_fkey"
            columns: ["away_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fixtures_home_team_id_fkey"
            columns: ["home_team_id"]
            isOneToOne: false
            referencedRelation: "teams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "fixtures_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
        ]
      }
      leagues: {
        Row: {
          api_league_id: number
          country: string
          id: number
          name: string
          season: number
          slug: string
        }
        Insert: {
          api_league_id: number
          country: string
          id?: never
          name: string
          season: number
          slug: string
        }
        Update: {
          api_league_id?: number
          country?: string
          id?: never
          name?: string
          season?: number
          slug?: string
        }
        Relationships: []
      }
      predictions: {
        Row: {
          brier_score: number | null
          created_at: string
          final_away_goals: number | null
          final_home_goals: number | null
          fixture_id: number
          id: string
          locked_at: string
          log_loss: number | null
          model_version: string
          predicted_away_goals: number
          predicted_home_goals: number
          prob_away: number
          prob_draw: number
          prob_home: number
          published_at: string
          result: string | null
          scored_at: string | null
          source: string
          status: string
          tier: string
        }
        Insert: {
          brier_score?: number | null
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          fixture_id: number
          id?: string
          locked_at: string
          log_loss?: number | null
          model_version: string
          predicted_away_goals: number
          predicted_home_goals: number
          prob_away: number
          prob_draw: number
          prob_home: number
          published_at?: string
          result?: string | null
          scored_at?: string | null
          source: string
          status?: string
          tier?: string
        }
        Update: {
          brier_score?: number | null
          created_at?: string
          final_away_goals?: number | null
          final_home_goals?: number | null
          fixture_id?: number
          id?: string
          locked_at?: string
          log_loss?: number | null
          model_version?: string
          predicted_away_goals?: number
          predicted_home_goals?: number
          prob_away?: number
          prob_draw?: number
          prob_home?: number
          published_at?: string
          result?: string | null
          scored_at?: string | null
          source?: string
          status?: string
          tier?: string
        }
        Relationships: [
          {
            foreignKeyName: "predictions_fixture_id_fkey"
            columns: ["fixture_id"]
            isOneToOne: false
            referencedRelation: "fixtures"
            referencedColumns: ["id"]
          },
        ]
      }
      teams: {
        Row: {
          api_team_id: number
          id: number
          league_id: number
          name: string
          slug: string
        }
        Insert: {
          api_team_id: number
          id?: never
          league_id: number
          name: string
          slug: string
        }
        Update: {
          api_team_id?: number
          id?: never
          league_id?: number
          name?: string
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "teams_league_id_fkey"
            columns: ["league_id"]
            isOneToOne: false
            referencedRelation: "leagues"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
