import type { Metadata, Viewport } from 'next';
import { Archivo, Hanken_Grotesk, IBM_Plex_Mono } from 'next/font/google';
import { Analytics } from '@vercel/analytics/next';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import DisclaimerBanner from '@/components/DisclaimerBanner';
import { SITE_NAME, SITE_URL } from '@/lib/constants';
import { jsonLdScript, organizationJsonLd, websiteJsonLd } from '@/lib/jsonld';

// Three deliberate type roles (DESIGN.md §3), self-hosted via next/font with
// `display: swap` so there is no layout shift (§8 Core Web Vitals).
const archivo = Archivo({
  variable: '--font-archivo',
  subsets: ['latin'],
  display: 'swap',
});

const hanken = Hanken_Grotesk({
  variable: '--font-hanken',
  subsets: ['latin'],
  display: 'swap',
});

const plexMono = IBM_Plex_Mono({
  variable: '--font-plex-mono',
  subsets: ['latin'],
  weight: ['400', '500'],
  display: 'swap',
});

const DEFAULT_DESCRIPTION =
  'Football match probabilities and predicted scores, framed as analysis — not betting advice. Every prediction is locked at kickoff and scored in a permanent public ledger, wins and losses alike.';

// Global metadata, title template and Open Graph defaults (ARCHITECTURE.md §4,
// §11, §12). metadataBase uses NEXT_PUBLIC_SITE_URL with a localhost fallback.
export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: `${SITE_NAME} — transparent football analysis`,
    template: `%s · ${SITE_NAME}`,
  },
  description: DEFAULT_DESCRIPTION,
  applicationName: SITE_NAME,
  openGraph: {
    type: 'website',
    siteName: SITE_NAME,
    title: `${SITE_NAME} — transparent football analysis`,
    description: DEFAULT_DESCRIPTION,
    // No default `url` here on purpose: a hardcoded og:url would be inherited by
    // every page that does not set its own openGraph, pointing all of their
    // share cards at the homepage. Each route declares its own self-referential
    // og:url instead (resolved against metadataBase). (ARCHITECTURE.md §11)
  },
  twitter: {
    // The default social image is generated by app/opengraph-image.tsx (Next's
    // file-convention wiring populates openGraph.images/twitter automatically).
    card: 'summary_large_image',
    title: `${SITE_NAME} — transparent football analysis`,
    description: DEFAULT_DESCRIPTION,
  },
  robots: { index: true, follow: true },
  // PWA-lite (DESIGN.md §8): installable, fast repeat loads. Icons themselves
  // are wired automatically by the app/icon.tsx + app/apple-icon.tsx file
  // conventions; this just points at the manifest.
  manifest: '/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: SITE_NAME,
  },
};

// Separate from `metadata` per the Next.js viewport API — theme-color must be
// set here, not in `metadata` (DESIGN.md §2 `--bg` token, matching the
// manifest's background/theme colour so the browser chrome and the installed
// app never mismatch the page itself).
export const viewport: Viewport = {
  themeColor: '#0E1311',
  colorScheme: 'dark',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${archivo.variable} ${hanken.variable} ${plexMono.variable} dark h-full antialiased`}
    >
      <body className="flex min-h-full flex-col bg-bg text-fg">
        {/* Site-wide entity JSON-LD (ARCHITECTURE.md §11) — consolidates every
            indexed page under one Organization/WebSite identity. Plain
            name + url only, no logo/marks (§13). Data, not executable JS, so
            the page stays zero-client-JS (DESIGN.md §8). */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdScript(organizationJsonLd()) }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdScript(websiteJsonLd()) }}
        />
        {/* Persistent disclaimer on every page (ARCHITECTURE.md §13). */}
        <DisclaimerBanner />
        <Header />
        {/* W4: the shell widens to max-w-6xl at lg (header/main/footer together
            so edges align) and the home page composes a 12-col grid inside it. */}
        <main className="mx-auto w-full max-w-screen-md flex-1 px-4 py-6 lg:max-w-6xl">
          {children}
        </main>
        <Footer />
        {/* Cookieless Vercel Web Analytics (ARCHITECTURE.md §12) — no consent
            banner required; this is the only client script this layout adds.
            Rendered only when the build actually runs on Vercel: the script it
            injects (/_vercel/insights/script.js) is served by Vercel's edge, so
            in a locally-served production build (the E2E webServer) it 404s and
            trips the "no console errors" gate. */}
        {process.env.VERCEL ? <Analytics /> : null}
      </body>
    </html>
  );
}
